export const GET_ALL_TASKS = 'GET_ALL_TASKS';
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS';
export const GET_ALL_TASKS_ERROR = 'GET_ALL_TASKS_ERROR';

export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';

export const CHANGE_TASK = 'CHANGE_TASK';
export const CHANGE_TASK_SUCCESS = 'CHANGE_TASK_SUCCESS';
export const CHANGE_TASK_ERROR = 'CHANGE_TASK_ERROR';