export const REGISTER_STUDENT = 'REGISTER_STUDENT';
export const STUDENT_COMPLETED_REGISTRATION = 'STUDENT_COMPLETED_REGISTRATION';
export const REGISTRATION_STUDENT_FAILED = 'REGISTRATION_STUDENT_FAILED';
export const STUDENT_REGISTRATION_LOGICAL_ERROR_OCCURREDD = 'STUDENT_REGISTRATION_LOGICAL_ERROR_OCCURREDD';