export const REGISTER_TEACHER = 'REGISTER_TEACHER';
export const TEACHER_COMPLETED_REG = 'TEACHER_COMPLETED_REGISTRATION';
export const REG_TEACHER_FAILED = 'REGISTRATION_TEACHER_FAILED';
export const TEACHER_REG_LOGICAL_ERROR_HAPPENED = 'TEACHER_REGISTRATION_LOGICAL_ERROR_HAPPENED';
export const SHOW_TEACHER_REG_MODAL = 'SHOW_TEACHER_REGISTRATION_MODAL';
export const HIDE_TEACHER_REG_MODAL = 'HIDE_TEACHER_REGISTRATION_MODAL';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';