export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';
export const WATCH_CURRENT_GROUP = 'WATCH_CURRENT_GROUP';
export const CHANGE_UPDATING_STATUS_CURRENT_GROUP = 'CHANGE_UPDATING_STATUS_CURRENT_GROUP';
