export const CALC = 'CALC';
export const APP_LOAD = 'APP_LOAD';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const REGISTER_STUDENT = 'REGISTER_STUDENT';
export const REGISTRATION_STUDENT = 'REGISTRATION_STUDENT';
export const REGISTRATION_STUDENT_ERROR = 'REGISTRATION_STUDENT_ERROR';
export const HIDE_STUDENT_REGISTERED_MODAL = 'HIDE_STUDENT_REGISTERED_MODAL';

export const REGISTER_TEACHER = 'REGISTER_TEACHER';
export const REGISTRATION_TEACHER_RESPONSE = 'REGISTRATION_TEACHER_RESPONSE';
export const REGISTRATION_TEACHER_ERROR = 'REGISTRATION_TEACHER_ERROR';
export const SHOW_TEACHER_REGISTERED_MODAL = 'SHOW_TEACHER_REGISTERED_MODAL';
export const HIDE_TEACHER_REGISTERED_MODAL = 'HIDE_TEACHER_REGISTERED_MODAL';
export const HIDE_TEACHER_RESPONSE_MODAL = 'HIDE_TEACHER_RESPONSE_MODAL';