export const CALC = "CALC";
export const APP_LOAD = "APP_LOAD";

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const REGISTER_STUDENT = 'REGISTER_STUDENT';
export const VALIDATE_FIRST_NAME_ENG = 'VALIDATE_FIRST_NAME_ENG';
export const NOT_UNIQUE_EMAIL = 'NOT_UNIQUE_EMAIL';
export const GROUP_NOT_FOUND = 'GROUP_NOT_FOUND';
export const REGISTRATION_STUDENT_SUCCESS = 'REGISTRATION_STUDENT_SUCCESS';