export const REGISTER_TEACHER = 'REGISTER_TEACHER';
export const REGISTRATION_TEACHER_RESPONSE = 'REGISTRATION_TEACHER_RESPONSE';
export const REGISTRATION_TEACHER_ERROR = 'REGISTRATION_TEACHER_ERROR';
export const SHOW_TEACHER_REGISTERED_MODAL = 'SHOW_TEACHER_REGISTERED_MODAL';
export const HIDE_TEACHER_REGISTERED_MODAL = 'HIDE_TEACHER_REGISTERED_MODAL';
export const HIDE_TEACHER_RESPONSE_MODAL = 'HIDE_TEACHER_RESPONSE_MODAL';