export const REGISTER_STUDENT = 'REGISTER_STUDENT';
export const STUDENT_COMPLETED_REGISTER = 'STUDENT_COMPLETED_REGISTER';
export const REGISTER_STUDENT_FAILED = 'REGISTER_STUDENT_FAILED';
export const STUDENT_REGISTER_ERROR_HAPPENED = 'STUDENT_REGISTER_ERROR_HAPPENED';
