export const REGISTER_STUDENT = 'REGISTER_STUDENT';
export const STUDENT_COMPLETED_REG = 'STUDENT_COMPLETED_REGISTRATION';
export const REG_STUDENT_FAILED = 'REGISTRATION_STUDENT_FAILED';
export const STUDENT_REG_LOGICAL_ERROR_HAPPENED = 'STUDENT_REGISTRATION_LOGICAL_ERROR_HAPPENED';